#!/bin/bash
# VERIFICAR CAMBIOS - Script rápido para ver lo que cambió

echo "═══════════════════════════════════════════════════════════════"
echo "📊 CAMBIOS EN PRESENTACIÓN DE ALERTAS"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "✅ ARCHIVOS MODIFICADOS:"
echo "  1. web/monitoreo/views.py"
echo "     - Nueva función: _extract_ml_metrics()"
echo "     - Mejorada: _format_alert_for_dashboard()"
echo ""

echo "  2. web/monitoreo/templates/monitoreo/alertas.html"
echo "     - Rediseñada completamente con tarjetas visuales"
echo "     - Muestra: ML metrics, OSINT, Recomendaciones"
echo ""

echo "  3. web/monitoreo/templates/monitoreo/overview.html"
echo "     - Mejorada presentación de alerta crítica"
echo "     - Más detalles de ML y OSINT"
echo "     - Timeline mejorado con métricas"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "🎯 INFORMACIÓN MOSTRADA EN CADA ALERTA"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Datos de ML (extraídos del campo 'explicacion'):"
echo "  • Accuracy y F1 Score"
echo "  • Riesgo (%)"
echo "  • Criticidad (0-5)"
echo "  • Severidad"
echo "  • OSINT Score"
echo "  • AbuseIPDB (%)"
echo "  • OTX Pulses"
echo "  • Ajuste Contextual"
echo ""

echo "Datos OSINT (contexto resumido):"
echo "  • VirusTotal detections"
echo "  • AbuseIPDB confidence"
echo "  • OTX pulse count"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "🚀 CÓMO ACCEDER"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Login:"
echo "   URL: http://127.0.0.1:8000/login/"
echo "   Usuario: admin"
echo "   Contraseña: AdminPassword123!"
echo ""

echo "2. Ver alertas en Panel Principal:"
echo "   URL: http://127.0.0.1:8000/"
echo "   (Overview con alerta crítica + timeline)"
echo ""

echo "3. Ver todas las alertas en detalle:"
echo "   URL: http://127.0.0.1:8000/alertas/"
echo "   (Tarjetas con información completa)"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "📝 EJEMPLO DE ALERTA FORMATEADA"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "╔═════════════════════════════════════════════════════════════╗"
echo "║ SCORE: 95    05 May 2026 · 12:34:56                        ║"
echo "║ FIRMA: PRUEBA CONTROL GOOGLE DNS                           ║"
echo "║                                                             ║"
echo "║ [Critical] [Elevada]                                        ║"
echo "║                                                             ║"
echo "║ Origen: 192.168.1.1 → Destino: 8.8.8.8                    ║"
echo "║                                                             ║"
echo "║ ┌─────────────────────────────────────────────────────────┐║"
echo "║ │ 🤖 ML: acc=0.93, f1=0.94                                │║"
echo "║ │ 📊 Riesgo: 59%                                          │║"
echo "║ │ ⚠️  Criticidad: 4/5                                      │║"
echo "║ │ 🔴 Severidad: Baja                                      │║"
echo "║ │ 🌐 OSINT Score: 45.5                                    │║"
echo "║ │ ⚡ AbuseIPDB: 62%                                        │║"
echo "║ │ 📡 OTX Pulses: 37                                       │║"
echo "║ │ 🔧 Ajuste: +29.4                                        │║"
echo "║ └─────────────────────────────────────────────────────────┘║"
echo "║                                                             ║"
echo "║ 🔍 OSINT: VT: 62 · Abuse: 62 · OTX: 37                    ║"
echo "║                                                             ║"
echo "║ 💡 Recomendación:                                           ║"
echo "║ Escalar al analista responsable para revision detallada.   ║"
echo "╚═════════════════════════════════════════════════════════════╝"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "✨ LISTO PARA USAR"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Los cambios ya están implementados. Solo necesitas:"
echo "  1. Asegurarte de estar autenticado"
echo "  2. Navegar a /alertas/ para ver las tarjetas mejoradas"
echo "  3. Ver el overview para la alerta más crítica detallada"
echo ""
