# Generated by Django 6.0.4 on 2026-04-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('ip_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_destino', models.CharField(blank=True, max_length=50, null=True)),
                ('firma', models.TextField(blank=True, null=True)),
                ('severidad', models.IntegerField(blank=True, null=True)),
                ('reputacion_osint', models.IntegerField(blank=True, null=True)),
                ('prioridad_ia', models.FloatField(blank=True, null=True)),
                ('explicacion', models.TextField(blank=True, null=True)),
                ('recomendacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alertas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('criticidad', models.IntegerField(default=1)),
            ],
        ),
    ]
