# Generated by Django 6.0.4 on 2026-05-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0006_monitoredendpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuricataConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interfaces', models.TextField(help_text='Interfaces de red a monitorear, separadas por comas (ej: eth0,eth1)')),
                ('is_active', models.BooleanField(default=True, help_text='Si la configuración está activa')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Suricata',
                'verbose_name_plural': 'Configuraciones Suricata',
            },
        ),
    ]
