ALTER TABLE alertas
ADD COLUMN IF NOT EXISTS vt_malicious INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS vt_suspicious INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS vt_reputation INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS abuse_confidence INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS abuse_reports INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS gn_noise BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS gn_riot BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS gn_classification VARCHAR(50) DEFAULT 'unknown',
ADD COLUMN IF NOT EXISTS otx_pulse_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS otx_tags TEXT,
ADD COLUMN IF NOT EXISTS otx_malware_families TEXT,
ADD COLUMN IF NOT EXISTS osint_score DOUBLE PRECISION DEFAULT 0;
